name: Publish development release

# Controls when the action will run
on:
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Workflows
  jar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
        
    - name: Set up JDK 8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
        
    - name: Fix gradlew file permissions
      run: chmod +x gradlew

    - name: Build jar
      run: ./gradlew desktop:dist
        
    - name: Upload jar as a release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: desktop/build/libs/*.jar
        file_glob: true
        tag: v-dev
        overwrite: true
        prerelease: true
        body: "Latest bleeding edge version of Zoned. Might be buggy"
