name: Publish development release

# Controls when the action will run
on:
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Workflows
  release_development_builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
        
    - name: Set up JDK 8
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.8
        
    - name: Install NDK
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
        
    - name: Fix gradlew file permissions
      run: chmod +x gradlew

    - name: Build jar
      run: ./gradlew desktop:dist
        
    - name: Build apk
      run: ./gradlew android:assembleDebug
        
    - name: Cleanup previous tags and releases
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        delete_release: true
        tag_name: v-dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload jar release
      uses: kittaakos/upload-release-action@GH-26
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: desktop/build/libs/*.jar
        file_glob: true
        tag: v-dev
        overwrite: true
        prerelease: true
        release_name: "Zoned Developer Build"
        body: "Latest bleeding edge version of Zoned"
        
    - name: Upload apk release
      uses: kittaakos/upload-release-action@GH-26
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: android/build/outputs/apk/debug/*.apk
        file_glob: true
        tag: v-dev
        overwrite: true
        prerelease: true

